version: '3'

services:
  app:
    build: .
    # network_mode: host
    ports:
      - "5000:5000"  # Flask
      - "8765:8765"  # WebSocket
      - "4173:4173"  # React Vite
    environment:
      - BROKER=192.168.88.228
      - PORT=1883
      - USERNAME=admin
      - PASSWORD=admin
      - APPLICATION_ID=da361409-e975-4d8d-80cf-e049887d276a
    volumes:
      - ./data:/data
    restart: unless-stopped
