version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"  # Flask
      - "8765:8765"  # WebSocket
      - "4173:4173"  # React Vite
    environment:
      - BROKER=192.168.88.85
      - PORT=1883
      - USERNAME=admin
      - PASSWORD=admin
      - APPLICATION_ID=8F7226Aa-6f8d-4e5e-9229-67bd09308A94
    volumes:
      - ./data:/data
    restart: unless-stopped
